version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --max-connections=1000
    container_name: streaming_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: streaming_db
      MYSQL_USER: user_streaming
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: